name: cardiap
channels:
- bioconda
- conda-forge
- defaults
- salilab
dependencies:
  - python=3.8.10
  - pip=20.0.2
  - pip:            
    - interactivecrop==0.0.10              
    - ipykernel==5.5.0               
    - ipython==7.21.0             
    - ipywidgets==7.6.5         
    - jupyterlab==3.0.9               
    - jupyterlab-widgets==1.0.2               
    - matplotlib==3.1.3            
    - notebook==6.2.0               
    - numpy==1.23.4              
    - opencv-python==4.5.1.48         
    - pandas== 1.2.2               
    - PeakUtils==1.3.3         
    - Pillow==9.2.0      
    - requests==2.22.0            
    - scipy==1.9.0               
    - seaborn==0.11.1              
    - setuptools==45.2.0